CeladonCity_NetworkEnthusiastHouse_F1_Text_Info::
	.string "Welcome to CELADON NETWORK CLUB!\n"
    .string "Everyone here loves technology.\p"
	.string "You can get connected with the\n"
	.string "computer to my right.\p" 
	.string "Then head downstairs to try the\n"
	.string "demos our members have made.$"

CeladonCity_NetworkEnthusiastHouse_F1_Text_ShouldStartConnection::
	.string "Start Pokecom channel connection?$"

CeladonCity_NetworkEnthusiastHouse_F1_Text_PleaseWaitForLink::
	.string "Please wait.\n"
	.string "… … Hold B Button: Cancel$"


CeladonCity_NetworkEnthusiastHouse_F1_Text_PlaceHolder::
	.string "This is some placeholder text$"

CeladonCity_NetworkEnthusiastHouse_F1_Text_ConnectionFailed::
	.string "{COLOR RED}{SHADOW LIGHT_RED}FAILED$"

CeladonCity_NetworkEnthusiastHouse_F1_Text_ConnectionLocal::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PLUGGED IN - NO INTERNET$"

CeladonCity_NetworkEnthusiastHouse_F1_Text_ConnectionOnline::
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}ONLINE$"
