var StringHelper = require('./pokeString.js');

class TrainerHelper {

    static createDefault() {

        let trainerItems = new TrainerItems(ITEM_FULL_RESTORE,ITEM_NONE,ITEM_NONE,ITEM_NONE);
        let pokemon1Moves = new Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE);
        let pokemon1 = new Pokemon(255, 10, SPECIES_MAGIKARP, ITEM_LEFTOVERS, pokemon1Moves, "Bob");
        let party = new Party(pokemon1, TrainerHelper.emptyMon("Jim"), TrainerHelper.emptyMon("Amy"), TrainerHelper.emptyMon(), TrainerHelper.emptyMon(), TrainerHelper.emptyMon());
        let overworldText = "Never underestimate a fishermans rod.";
        let trainerAi = AI_SCRIPT_CHECK_BAD_MOVE | AI_SCRIPT_TRY_TO_FAINT | AI_SCRIPT_CHECK_VIABILITY;
        let trainerName = "Magicarp Mike";

        return new Trainer(OBJ_EVENT_GFX_FISHERMAN, overworldText, TRAINER_CLASS_FISHERMAN, TRAINER_ENCOUNTER_MUSIC_COOL, TRAINER_PIC_FISHERMAN, trainerItems, trainerName, trainerAi, party);
    }

    static defaultPokemon() {
        let pokemon1Moves = new Moves(MOVE_SPLASH, MOVE_NONE, MOVE_NONE, MOVE_NONE);
        return new Pokemon(255, 69, SPECIES_MAGIKARP, ITEM_LEFTOVERS, pokemon1Moves, "Bob");
    } 

    static getBattle1Pokemon() {
        return trainer1.party.slot1;
    }

    static updateTrainer1Pokemon(data) {
        let pokemon1Moves = new Moves(data.mon1Data.move1, data.mon1Data.move2, data.mon1Data.move3, data.mon1Data.move4);
        trainer1.party.slot1 = new Pokemon(255, data.mon1Data.level, data.mon1Data.species, data.mon1Data.item, pokemon1Moves, data.mon1Data.nickname);

        let pokemon2Moves = new Moves(data.mon2Data.move1, data.mon2Data.move2, data.mon2Data.move3, data.mon2Data.move4);
        trainer1.party.slot2 = new Pokemon(255, data.mon2Data.level, data.mon2Data.species, data.mon2Data.item, pokemon2Moves, data.mon2Data.nickname);

        let pokemon3Moves = new Moves(data.mon3Data.move1, data.mon3Data.move2, data.mon3Data.move3, data.mon3Data.move4);
        trainer1.party.slot3 = new Pokemon(255, data.mon3Data.level, data.mon3Data.species, data.mon3Data.item, pokemon3Moves, data.mon3Data.nickname);
    }

    static getTrainer() {
        return trainer1;
    }

    static emptyMon(name) {
        let pokemonMoves = new Moves(0, 0, 0, 0);

        if (!name){
            name = "   ";
        }

        return new Pokemon(0, 1, 0, 0, pokemonMoves, name);
    }

}

class Trainer {

    constructor(owSpriteNo, owDialog, trainerClass, encounterMusic, trainerPic, trainerItems, trainerName, trainerAI, party) {
      this.owSpriteNo      = owSpriteNo;
      this.owDialog        = StringHelper.convertMessageToHex(owDialog);
      this.owDialog_raw    = owDialog;
      this.trainerClass    = trainerClass;
      this.encounterMusic  = encounterMusic;
      this.trainerPic      = trainerPic;
      this.trainerItems    = trainerItems;
      this.trainerName     = StringHelper.convertMessageToHex(trainerName);
      this.trainerName_raw = trainerName;
      this.trainerAI       = trainerAI;
      this.party           = party;
      this.wins            = 0;
      this.losses          = 0;
    }

    toString() {
        return speciesNames.get(this.party.slot1.species) + ", " +
               speciesNames.get(this.party.slot2.species) + ", " +
               speciesNames.get(this.party.slot3.species);
        // return this.trainerName_raw + "\nWins: " + this.wins + " Losses: " + this.losses;
    }

    get3MonTeam() {

        var mergedArray = new Uint8Array(3 * 16);

        mergedArray.set(this.party.slot1.get16ByteDataArray(), 0 * 16);
        mergedArray.set(this.party.slot2.get16ByteDataArray(), 1 * 16);
        mergedArray.set(this.party.slot3.get16ByteDataArray(), 2 * 16);
        
        return mergedArray;
    }

}

class TrainerItems {
   constructor(slot1, slot2, slot3, slot4) {
       this.slot1 = slot1;
       this.slot2 = slot2;
       this.slot3 = slot3;
       this.slot4 = slot4;
   }
}

class Party {
   constructor(slot1, slot2, slot3, slot4, slot5, slot6) {
       this.slot1 = slot1;
       this.slot2 = slot2;
       this.slot3 = slot3;
       this.slot4 = slot4;
       this.slot5 = slot5;
       this.slot6 = slot6;
   }
}

class Pokemon {
    constructor(iv, level, species, heldItem, moves, nickname) {
        this.iv       = iv;
        this.level    = level;
        this.species  = species;
        this.heldItem = heldItem;
        this.moves    = moves;
        this.nickname = nickname;
        this.name     = StringHelper.convertMessageToHex(nickname);
    }

    get16ByteDataArray() {
        let data = new Uint8Array(16);
        data[0] = (this.species & 0xff);
        data[1] = this.species >> 8;
        
        data[2] = this.level;

        data[3] = (this.heldItem & 0xff);
        data[4] = this.heldItem >> 8;

        data.set(this.moves.getDataArray(), 5)

        data[13] = this.name[0];
        data[14] = this.name[1];
        data[15] = this.name[2];

        return data;
    }
}

class Moves {
   constructor(slot1, slot2, slot3, slot4) {
       this.slot1 = slot1;
       this.slot2 = slot2;
       this.slot3 = slot3;
       this.slot4 = slot4;
   }

    getDataArray() {
        let data = new Uint8Array(8);
        data[0] = (this.slot1 & 0xff);
        data[1] = (this.slot1 & 0xff) << 8;

        data[2] = (this.slot2 & 0xff);
        data[3] = (this.slot2 & 0xff) << 8;

        data[4] = (this.slot3 & 0xff);
        data[5] = (this.slot3 & 0xff) << 8;

        data[6] = (this.slot4 & 0xff);
        data[7] = (this.slot4 & 0xff) << 8;

        return data;
    }
}

const ITEM_NONE = 0;

/* TRANIER ITEMS */
const ITEM_POTION        = 13;
const ITEM_ANTIDOTE      = 14;
const ITEM_BURN_HEAL     = 15;
const ITEM_ICE_HEAL      = 16;
const ITEM_AWAKENING     = 17;
const ITEM_PARALYZE_HEAL = 18;
const ITEM_FULL_RESTORE  = 19;
const ITEM_MAX_POTION    = 20;
const ITEM_HYPER_POTION  = 21;
const ITEM_SUPER_POTION  = 22;
const ITEM_FULL_HEAL     = 23;
const ITEM_REVIVE        = 24;
const ITEM_MAX_REVIVE    = 25;
const ITEM_FRESH_WATER   = 26;
const ITEM_SODA_POP      = 27;
const ITEM_LEMONADE      = 28;
const ITEM_MOOMOO_MILK   = 29;
const ITEM_ENERGY_POWDER = 30;
const ITEM_ENERGY_ROOT   = 31;
const ITEM_HEAL_POWDER   = 32;
const ITEM_REVIVAL_HERB  = 33;
const ITEM_ETHER         = 34;
const ITEM_MAX_ETHER     = 35;
const ITEM_ELIXIR        = 36;
const ITEM_MAX_ELIXIR    = 37;
const ITEM_LAVA_COOKIE   = 38;
const ITEM_BLUE_FLUTE    = 39;
const ITEM_YELLOW_FLUTE  = 40;
const ITEM_RED_FLUTE     = 41;
const ITEM_BLACK_FLUTE   = 42;
const ITEM_WHITE_FLUTE   = 43;
const ITEM_BERRY_JUICE   = 44;

const ITEM_GUARD_SPEC  = 73;
const ITEM_DIRE_HIT    = 74;
const ITEM_X_ATTACK    = 75;
const ITEM_X_DEFEND    = 76;
const ITEM_X_SPEED     = 77;
const ITEM_X_ACCURACY  = 78;
const ITEM_X_SPECIAL   = 79;

 /* OW SPRITES */
const OBJ_EVENT_GFX_BRENDAN_NORMAL             =   0;
const OBJ_EVENT_GFX_BRENDAN_MACH_BIKE          =   1;
const OBJ_EVENT_GFX_BRENDAN_SURFING            =   2;
const OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE         =   3;
const OBJ_EVENT_GFX_QUINTY_PLUMP               =   4;
const OBJ_EVENT_GFX_NINJA_BOY                  =   5;
const OBJ_EVENT_GFX_TWIN                       =   6;
const OBJ_EVENT_GFX_BOY_1                      =   7;
const OBJ_EVENT_GFX_GIRL_1                     =   8;
const OBJ_EVENT_GFX_BOY_2                      =   9;
const OBJ_EVENT_GFX_GIRL_2                     =  10;
const OBJ_EVENT_GFX_LITTLE_BOY                 =  11;
const OBJ_EVENT_GFX_LITTLE_GIRL                =  12;
const OBJ_EVENT_GFX_BOY_3                      =  13;
const OBJ_EVENT_GFX_GIRL_3                     =  14;
const OBJ_EVENT_GFX_RICH_BOY                   =  15;
const OBJ_EVENT_GFX_WOMAN_1                    =  16;
const OBJ_EVENT_GFX_FAT_MAN                    =  17;
const OBJ_EVENT_GFX_POKEFAN_F                  =  18;
const OBJ_EVENT_GFX_MAN_1                      =  19;
const OBJ_EVENT_GFX_WOMAN_2                    =  20;
const OBJ_EVENT_GFX_EXPERT_M                   =  21;
const OBJ_EVENT_GFX_EXPERT_F                   =  22;
const OBJ_EVENT_GFX_MAN_2                      =  23;
const OBJ_EVENT_GFX_WOMAN_3                    =  24;
const OBJ_EVENT_GFX_POKEFAN_M                  =  25;
const OBJ_EVENT_GFX_WOMAN_4                    =  26;
const OBJ_EVENT_GFX_COOK                       =  27;
const OBJ_EVENT_GFX_LINK_RECEPTIONIST          =  28;
const OBJ_EVENT_GFX_OLD_MAN                    =  29;
const OBJ_EVENT_GFX_OLD_WOMAN                  =  30;
const OBJ_EVENT_GFX_CAMPER                     =  31;
const OBJ_EVENT_GFX_PICNICKER                  =  32;
const OBJ_EVENT_GFX_MAN_3                      =  33;
const OBJ_EVENT_GFX_WOMAN_5                    =  34;
const OBJ_EVENT_GFX_YOUNGSTER                  =  35;
const OBJ_EVENT_GFX_BUG_CATCHER                =  36;
const OBJ_EVENT_GFX_PSYCHIC_M                  =  37;
const OBJ_EVENT_GFX_SCHOOL_KID_M               =  38;
const OBJ_EVENT_GFX_MANIAC                     =  39;
const OBJ_EVENT_GFX_HEX_MANIAC                 =  40;
const OBJ_EVENT_GFX_RAYQUAZA_STILL             =  41;
const OBJ_EVENT_GFX_SWIMMER_M                  =  42;
const OBJ_EVENT_GFX_SWIMMER_F                  =  43;
const OBJ_EVENT_GFX_BLACK_BELT                 =  44;
const OBJ_EVENT_GFX_BEAUTY                     =  45;
const OBJ_EVENT_GFX_SCIENTIST_1                =  46;
const OBJ_EVENT_GFX_LASS                       =  47;
const OBJ_EVENT_GFX_GENTLEMAN                  =  48;
const OBJ_EVENT_GFX_SAILOR                     =  49;
const OBJ_EVENT_GFX_FISHERMAN                  =  50;
const OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M       =  51;
const OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F       =  52;
const OBJ_EVENT_GFX_TUBER_F                    =  53;
const OBJ_EVENT_GFX_TUBER_M                    =  54;
const OBJ_EVENT_GFX_HIKER                      =  55;
const OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M       =  56;
const OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F       =  57;
const OBJ_EVENT_GFX_NURSE                      =  58;
const OBJ_EVENT_GFX_ITEM_BALL                  =  59;
const OBJ_EVENT_GFX_BERRY_TREE                 =  60;
const OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES    =  61;
const OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES     =  62;
const OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE          =  63;
const OBJ_EVENT_GFX_PROF_BIRCH                 =  64;
const OBJ_EVENT_GFX_MAN_4                      =  65;
const OBJ_EVENT_GFX_MAN_5                      =  66;
const OBJ_EVENT_GFX_REPORTER_M                 =  67;
const OBJ_EVENT_GFX_REPORTER_F                 =  68;
const OBJ_EVENT_GFX_BARD                       =  69;
const OBJ_EVENT_GFX_ANABEL                     =  70;
const OBJ_EVENT_GFX_TUCKER                     =  71;
const OBJ_EVENT_GFX_GRETA                      =  72;
const OBJ_EVENT_GFX_SPENSER                    =  73;
const OBJ_EVENT_GFX_NOLAND                     =  74;
const OBJ_EVENT_GFX_LUCY                       =  75;
const OBJ_EVENT_GFX_UNUSED_NATU_DOLL           =  76;
const OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL      =  77;
const OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL       =  78;
const OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL         =  79;
const OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL        =  80;
const OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL       =  81;
const OBJ_EVENT_GFX_CUTTABLE_TREE              =  82;
const OBJ_EVENT_GFX_MART_EMPLOYEE              =  83;
const OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN         =  84;
const OBJ_EVENT_GFX_TEALA                      =  85;
const OBJ_EVENT_GFX_BREAKABLE_ROCK             =  86;
const OBJ_EVENT_GFX_PUSHABLE_BOULDER           =  87;
const OBJ_EVENT_GFX_MR_BRINEYS_BOAT            =  88;
const OBJ_EVENT_GFX_MAY_NORMAL                 =  89;
const OBJ_EVENT_GFX_MAY_MACH_BIKE              =  90;
const OBJ_EVENT_GFX_MAY_ACRO_BIKE              =  91;
const OBJ_EVENT_GFX_MAY_SURFING                =  92;
const OBJ_EVENT_GFX_MAY_FIELD_MOVE             =  93;
const OBJ_EVENT_GFX_TRUCK                      =  94;
const OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX      =  95;
const OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY       =  96;
const OBJ_EVENT_GFX_BIRCHS_BAG                 =  97;
const OBJ_EVENT_GFX_ZIGZAGOON_1                =  98;
const OBJ_EVENT_GFX_ARTIST                     =  99;
const OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       = 100;
const OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    = 101;
const OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    = 102;
const OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      = 103;
const OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   = 104;
const OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           = 105;
const OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        = 106;
const OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        = 107;
const OBJ_EVENT_GFX_RIVAL_MAY_SURFING          = 108;
const OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       = 109;
const OBJ_EVENT_GFX_CAMERAMAN                  = 110;
const OBJ_EVENT_GFX_BRENDAN_UNDERWATER         = 111;
const OBJ_EVENT_GFX_MAY_UNDERWATER             = 112;
const OBJ_EVENT_GFX_MOVING_BOX                 = 113;
const OBJ_EVENT_GFX_CABLE_CAR                  = 114;
const OBJ_EVENT_GFX_SCIENTIST_2                = 115;
const OBJ_EVENT_GFX_DEVON_EMPLOYEE             = 116;
const OBJ_EVENT_GFX_AQUA_MEMBER_M              = 117;
const OBJ_EVENT_GFX_AQUA_MEMBER_F              = 118;
const OBJ_EVENT_GFX_MAGMA_MEMBER_M             = 119;
const OBJ_EVENT_GFX_MAGMA_MEMBER_F             = 120;
const OBJ_EVENT_GFX_SIDNEY                     = 121;
const OBJ_EVENT_GFX_PHOEBE                     = 122;
const OBJ_EVENT_GFX_GLACIA                     = 123;
const OBJ_EVENT_GFX_DRAKE                      = 124;
const OBJ_EVENT_GFX_ROXANNE                    = 125;
const OBJ_EVENT_GFX_BRAWLY                     = 126;
const OBJ_EVENT_GFX_WATTSON                    = 127;
const OBJ_EVENT_GFX_FLANNERY                   = 128;
const OBJ_EVENT_GFX_NORMAN                     = 129;
const OBJ_EVENT_GFX_WINONA                     = 130;
const OBJ_EVENT_GFX_LIZA                       = 131;
const OBJ_EVENT_GFX_TATE                       = 132;
const OBJ_EVENT_GFX_WALLACE                    = 133;
const OBJ_EVENT_GFX_STEVEN                     = 134;
const OBJ_EVENT_GFX_WALLY                      = 135;
const OBJ_EVENT_GFX_LITTLE_BOY_3               = 136;
const OBJ_EVENT_GFX_BRENDAN_FISHING            = 137;
const OBJ_EVENT_GFX_MAY_FISHING                = 138;
const OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      = 139;
const OBJ_EVENT_GFX_SS_TIDAL                   = 140;
const OBJ_EVENT_GFX_SUBMARINE_SHADOW           = 141;
const OBJ_EVENT_GFX_PICHU_DOLL                 = 142;
const OBJ_EVENT_GFX_PIKACHU_DOLL               = 143;
const OBJ_EVENT_GFX_MARILL_DOLL                = 144;
const OBJ_EVENT_GFX_TOGEPI_DOLL                = 145;
const OBJ_EVENT_GFX_CYNDAQUIL_DOLL             = 146;
const OBJ_EVENT_GFX_CHIKORITA_DOLL             = 147;
const OBJ_EVENT_GFX_TOTODILE_DOLL              = 148;
const OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            = 149;
const OBJ_EVENT_GFX_MEOWTH_DOLL                = 150;
const OBJ_EVENT_GFX_CLEFAIRY_DOLL              = 151;
const OBJ_EVENT_GFX_DITTO_DOLL                 = 152;
const OBJ_EVENT_GFX_SMOOCHUM_DOLL              = 153;
const OBJ_EVENT_GFX_TREECKO_DOLL               = 154;
const OBJ_EVENT_GFX_TORCHIC_DOLL               = 155;
const OBJ_EVENT_GFX_MUDKIP_DOLL                = 156;
const OBJ_EVENT_GFX_DUSKULL_DOLL               = 157;
const OBJ_EVENT_GFX_WYNAUT_DOLL                = 158;
const OBJ_EVENT_GFX_BALTOY_DOLL                = 159;
const OBJ_EVENT_GFX_KECLEON_DOLL               = 160;
const OBJ_EVENT_GFX_AZURILL_DOLL               = 161;
const OBJ_EVENT_GFX_SKITTY_DOLL                = 162;
const OBJ_EVENT_GFX_SWABLU_DOLL                = 163;
const OBJ_EVENT_GFX_GULPIN_DOLL                = 164;
const OBJ_EVENT_GFX_LOTAD_DOLL                 = 165;
const OBJ_EVENT_GFX_SEEDOT_DOLL                = 166;
const OBJ_EVENT_GFX_PIKA_CUSHION               = 167;
const OBJ_EVENT_GFX_ROUND_CUSHION              = 168;
const OBJ_EVENT_GFX_KISS_CUSHION               = 169;
const OBJ_EVENT_GFX_ZIGZAG_CUSHION             = 170;
const OBJ_EVENT_GFX_SPIN_CUSHION               = 171;
const OBJ_EVENT_GFX_DIAMOND_CUSHION            = 172;
const OBJ_EVENT_GFX_BALL_CUSHION               = 173;
const OBJ_EVENT_GFX_GRASS_CUSHION              = 174;
const OBJ_EVENT_GFX_FIRE_CUSHION               = 175;
const OBJ_EVENT_GFX_WATER_CUSHION              = 176;
const OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           = 177;
const OBJ_EVENT_GFX_BIG_RHYDON_DOLL            = 178;
const OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            = 179;
const OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          = 180;
const OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         = 181;
const OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         = 182;
const OBJ_EVENT_GFX_BIG_WAILMER_DOLL           = 183;
const OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          = 184;
const OBJ_EVENT_GFX_BIG_REGICE_DOLL            = 185;
const OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         = 186;
const OBJ_EVENT_GFX_LATIAS                     = 187;
const OBJ_EVENT_GFX_LATIOS                     = 188;
const OBJ_EVENT_GFX_GAMEBOY_KID                = 189;
const OBJ_EVENT_GFX_CONTEST_JUDGE              = 190;
const OBJ_EVENT_GFX_BRENDAN_WATERING           = 191;
const OBJ_EVENT_GFX_MAY_WATERING               = 192;
const OBJ_EVENT_GFX_BRENDAN_DECORATING         = 193;
const OBJ_EVENT_GFX_MAY_DECORATING             = 194;
const OBJ_EVENT_GFX_ARCHIE                     = 195;
const OBJ_EVENT_GFX_MAXIE                      = 196;
const OBJ_EVENT_GFX_KYOGRE_FRONT               = 197;
const OBJ_EVENT_GFX_GROUDON_FRONT              = 198;
const OBJ_EVENT_GFX_FOSSIL                     = 199;
const OBJ_EVENT_GFX_REGIROCK                   = 200;
const OBJ_EVENT_GFX_REGICE                     = 201;
const OBJ_EVENT_GFX_REGISTEEL                  = 202;
const OBJ_EVENT_GFX_SKITTY                     = 203;
const OBJ_EVENT_GFX_KECLEON                    = 204;
const OBJ_EVENT_GFX_KYOGRE_ASLEEP              = 205;
const OBJ_EVENT_GFX_GROUDON_ASLEEP             = 206;
const OBJ_EVENT_GFX_RAYQUAZA                   = 207;
const OBJ_EVENT_GFX_ZIGZAGOON_2                = 208;
const OBJ_EVENT_GFX_PIKACHU                    = 209;
const OBJ_EVENT_GFX_AZUMARILL                  = 210;
const OBJ_EVENT_GFX_WINGULL                    = 211;
const OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      = 212;
const OBJ_EVENT_GFX_TUBER_M_SWIMMING           = 213;
const OBJ_EVENT_GFX_AZURILL                    = 214;
const OBJ_EVENT_GFX_MOM                        = 215;
const OBJ_EVENT_GFX_LINK_BRENDAN               = 216;
const OBJ_EVENT_GFX_LINK_MAY                   = 217;
const OBJ_EVENT_GFX_JUAN                       = 218;
const OBJ_EVENT_GFX_SCOTT                      = 219;
const OBJ_EVENT_GFX_POOCHYENA                  = 220;
const OBJ_EVENT_GFX_KYOGRE_SIDE                = 221;
const OBJ_EVENT_GFX_GROUDON_SIDE               = 222;
const OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           = 223;
const OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         = 224;
const OBJ_EVENT_GFX_KIRLIA                     = 225;
const OBJ_EVENT_GFX_DUSCLOPS                   = 226;
const OBJ_EVENT_GFX_UNION_ROOM_NURSE           = 227;
const OBJ_EVENT_GFX_SUDOWOODO                  = 228;
const OBJ_EVENT_GFX_MEW                        = 229;
const OBJ_EVENT_GFX_RED                        = 230;
const OBJ_EVENT_GFX_LEAF                       = 231;
const OBJ_EVENT_GFX_DEOXYS                     = 232;
const OBJ_EVENT_GFX_DEOXYS_TRIANGLE            = 233;
const OBJ_EVENT_GFX_BRANDON                    = 234;
const OBJ_EVENT_GFX_LINK_RS_BRENDAN            = 235;
const OBJ_EVENT_GFX_LINK_RS_MAY                = 236;
const OBJ_EVENT_GFX_LUGIA                      = 237;
const OBJ_EVENT_GFX_HOOH                       = 238; 

 /* TRAINER CLASSES */
const TRAINER_CLASS_PKMN_TRAINER_1 = 0x0; 
const TRAINER_CLASS_PKMN_TRAINER_2 = 0x1; 
const TRAINER_CLASS_HIKER          = 0x2;
const TRAINER_CLASS_TEAM_AQUA      = 0x3;
const TRAINER_CLASS_PKMN_BREEDER   = 0x4;
const TRAINER_CLASS_COOLTRAINER    = 0x5;
const TRAINER_CLASS_BIRD_KEEPER    = 0x6;
const TRAINER_CLASS_COLLECTOR      = 0x7;
const TRAINER_CLASS_SWIMMER_M      = 0x8;
const TRAINER_CLASS_TEAM_MAGMA     = 0x9;
const TRAINER_CLASS_EXPERT         = 0xa;
const TRAINER_CLASS_AQUA_ADMIN     = 0xb;
const TRAINER_CLASS_BLACK_BELT     = 0xc;
const TRAINER_CLASS_AQUA_LEADER    = 0xd;
const TRAINER_CLASS_HEX_MANIAC     = 0xe;
const TRAINER_CLASS_AROMA_LADY     = 0xf;
const TRAINER_CLASS_RUIN_MANIAC    = 0x10;
const TRAINER_CLASS_INTERVIEWER    = 0x11;
const TRAINER_CLASS_TUBER_F        = 0x12;
const TRAINER_CLASS_TUBER_M        = 0x13;
const TRAINER_CLASS_LADY           = 0x14;
const TRAINER_CLASS_BEAUTY         = 0x15;
const TRAINER_CLASS_RICH_BOY       = 0x16;
const TRAINER_CLASS_POKEMANIAC     = 0x17;
const TRAINER_CLASS_GUITARIST      = 0x18;
const TRAINER_CLASS_KINDLER        = 0x19;
const TRAINER_CLASS_CAMPER         = 0x1a;
const TRAINER_CLASS_PICNICKER      = 0x1b;
const TRAINER_CLASS_BUG_MANIAC     = 0x1c;
const TRAINER_CLASS_PSYCHIC        = 0x1d;
const TRAINER_CLASS_GENTLEMAN      = 0x1e;
const TRAINER_CLASS_ELITE_FOUR     = 0x1f;
const TRAINER_CLASS_LEADER         = 0x20;
const TRAINER_CLASS_SCHOOL_KID     = 0x21;
const TRAINER_CLASS_SR_AND_JR      = 0x22;
const TRAINER_CLASS_WINSTRATE      = 0x23;
const TRAINER_CLASS_POKEFAN        = 0x24;
const TRAINER_CLASS_YOUNGSTER      = 0x25;
const TRAINER_CLASS_CHAMPION       = 0x26;
const TRAINER_CLASS_FISHERMAN      = 0x27;
const TRAINER_CLASS_TRIATHLETE     = 0x28;
const TRAINER_CLASS_DRAGON_TAMER   = 0x29;
const TRAINER_CLASS_NINJA_BOY      = 0x2a;
const TRAINER_CLASS_BATTLE_GIRL    = 0x2b;
const TRAINER_CLASS_PARASOL_LADY   = 0x2c;
const TRAINER_CLASS_SWIMMER_F      = 0x2d;
const TRAINER_CLASS_TWINS          = 0x2e;
const TRAINER_CLASS_SAILOR         = 0x2f;
const TRAINER_CLASS_COOLTRAINER_2  = 0x30;
const TRAINER_CLASS_MAGMA_ADMIN    = 0x31;
const TRAINER_CLASS_RIVAL          = 0x32;
const TRAINER_CLASS_BUG_CATCHER    = 0x33;
const TRAINER_CLASS_PKMN_RANGER    = 0x34;
const TRAINER_CLASS_MAGMA_LEADER   = 0x35;
const TRAINER_CLASS_LASS           = 0x36;
const TRAINER_CLASS_YOUNG_COUPLE   = 0x37;
const TRAINER_CLASS_OLD_COUPLE     = 0x38;
const TRAINER_CLASS_SIS_AND_BRO    = 0x39;
const TRAINER_CLASS_SALON_MAIDEN   = 0x3a;
const TRAINER_CLASS_DOME_ACE       = 0x3b;
const TRAINER_CLASS_PALACE_MAVEN   = 0x3c;
const TRAINER_CLASS_ARENA_TYCOON   = 0x3d;
const TRAINER_CLASS_FACTORY_HEAD   = 0x3e;
const TRAINER_CLASS_PIKE_QUEEN     = 0x3f;
const TRAINER_CLASS_PYRAMID_KING   = 0x40;
const TRAINER_CLASS_RS_PROTAG      = 0x41;

/* TRAINER MUSIC */
const TRAINER_ENCOUNTER_MUSIC_MALE        =  0;
const TRAINER_ENCOUNTER_MUSIC_FEMALE      =  1;
const TRAINER_ENCOUNTER_MUSIC_GIRL        =  2;
const TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS  =  3;
const TRAINER_ENCOUNTER_MUSIC_INTENSE     =  4;
const TRAINER_ENCOUNTER_MUSIC_COOL        =  5;
const TRAINER_ENCOUNTER_MUSIC_AQUA        =  6;
const TRAINER_ENCOUNTER_MUSIC_MAGMA       =  7;
const TRAINER_ENCOUNTER_MUSIC_SWIMMER     =  8;
const TRAINER_ENCOUNTER_MUSIC_TWINS       =  9;
const TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  = 10;
const TRAINER_ENCOUNTER_MUSIC_HIKER       = 11;
const TRAINER_ENCOUNTER_MUSIC_INTERVIEWER = 12;
const TRAINER_ENCOUNTER_MUSIC_RICH        = 13;

/* TRAINER PICS */
const TRAINER_PIC_HIKER                  =  0;
const TRAINER_PIC_AQUA_GRUNT_M           =  1;
const TRAINER_PIC_POKEMON_BREEDER_F      =  2;
const TRAINER_PIC_COOLTRAINER_M          =  3;
const TRAINER_PIC_BIRD_KEEPER            =  4;
const TRAINER_PIC_COLLECTOR              =  5;
const TRAINER_PIC_AQUA_GRUNT_F           =  6;
const TRAINER_PIC_SWIMMER_M              =  7;
const TRAINER_PIC_MAGMA_GRUNT_M          =  8;
const TRAINER_PIC_EXPERT_M               =  9;
const TRAINER_PIC_AQUA_ADMIN_M           = 10;
const TRAINER_PIC_BLACK_BELT             = 11;
const TRAINER_PIC_AQUA_ADMIN_F           = 12;
const TRAINER_PIC_AQUA_LEADER_ARCHIE     = 13;
const TRAINER_PIC_HEX_MANIAC             = 14;
const TRAINER_PIC_AROMA_LADY             = 15;
const TRAINER_PIC_RUIN_MANIAC            = 16;
const TRAINER_PIC_INTERVIEWER            = 17;
const TRAINER_PIC_TUBER_F                = 18;
const TRAINER_PIC_TUBER_M                = 19;
const TRAINER_PIC_COOLTRAINER_F          = 20;
const TRAINER_PIC_LADY                   = 21;
const TRAINER_PIC_BEAUTY                 = 22;
const TRAINER_PIC_RICH_BOY               = 23;
const TRAINER_PIC_EXPERT_F               = 24;
const TRAINER_PIC_POKEMANIAC             = 25;
const TRAINER_PIC_MAGMA_GRUNT_F          = 26;
const TRAINER_PIC_GUITARIST              = 27;
const TRAINER_PIC_KINDLER                = 28;
const TRAINER_PIC_CAMPER                 = 29;
const TRAINER_PIC_PICNICKER              = 30;
const TRAINER_PIC_BUG_MANIAC             = 31;
const TRAINER_PIC_POKEMON_BREEDER_M      = 32;
const TRAINER_PIC_PSYCHIC_M              = 33;
const TRAINER_PIC_PSYCHIC_F              = 34;
const TRAINER_PIC_GENTLEMAN              = 35;
const TRAINER_PIC_ELITE_FOUR_SIDNEY      = 36;
const TRAINER_PIC_ELITE_FOUR_PHOEBE      = 37;
const TRAINER_PIC_ELITE_FOUR_GLACIA      = 38;
const TRAINER_PIC_ELITE_FOUR_DRAKE       = 39;
const TRAINER_PIC_LEADER_ROXANNE         = 40;
const TRAINER_PIC_LEADER_BRAWLY          = 41;
const TRAINER_PIC_LEADER_WATTSON         = 42;
const TRAINER_PIC_LEADER_FLANNERY        = 43;
const TRAINER_PIC_LEADER_NORMAN          = 44;
const TRAINER_PIC_LEADER_WINONA          = 45;
const TRAINER_PIC_LEADER_TATE_AND_LIZA   = 46;
const TRAINER_PIC_LEADER_JUAN            = 47;
const TRAINER_PIC_SCHOOL_KID_M           = 48;
const TRAINER_PIC_SCHOOL_KID_F           = 49;
const TRAINER_PIC_SR_AND_JR              = 50;
const TRAINER_PIC_POKEFAN_M              = 51;
const TRAINER_PIC_POKEFAN_F              = 52;
const TRAINER_PIC_YOUNGSTER              = 53;
const TRAINER_PIC_CHAMPION_WALLACE       = 54;
const TRAINER_PIC_FISHERMAN              = 55;
const TRAINER_PIC_CYCLING_TRIATHLETE_M   = 56;
const TRAINER_PIC_CYCLING_TRIATHLETE_F   = 57;
const TRAINER_PIC_RUNNING_TRIATHLETE_M   = 58;
const TRAINER_PIC_RUNNING_TRIATHLETE_F   = 59;
const TRAINER_PIC_SWIMMING_TRIATHLETE_M  = 60;
const TRAINER_PIC_SWIMMING_TRIATHLETE_F  = 61;
const TRAINER_PIC_DRAGON_TAMER           = 62;
const TRAINER_PIC_NINJA_BOY              = 63;
const TRAINER_PIC_BATTLE_GIRL            = 64;
const TRAINER_PIC_PARASOL_LADY           = 65;
const TRAINER_PIC_SWIMMER_F              = 66;
const TRAINER_PIC_TWINS                  = 67;
const TRAINER_PIC_SAILOR                 = 68;
const TRAINER_PIC_MAGMA_ADMIN            = 69;
const TRAINER_PIC_WALLY                  = 70;
const TRAINER_PIC_BRENDAN                = 71;
const TRAINER_PIC_MAY                    = 72;
const TRAINER_PIC_BUG_CATCHER            = 73;
const TRAINER_PIC_POKEMON_RANGER_M       = 74;
const TRAINER_PIC_POKEMON_RANGER_F       = 75;
const TRAINER_PIC_MAGMA_LEADER_MAXIE     = 76;
const TRAINER_PIC_LASS                   = 77;
const TRAINER_PIC_YOUNG_COUPLE           = 78;
const TRAINER_PIC_OLD_COUPLE             = 79;
const TRAINER_PIC_SIS_AND_BRO            = 80;
const TRAINER_PIC_STEVEN                 = 81;
const TRAINER_PIC_SALON_MAIDEN_ANABEL    = 82;
const TRAINER_PIC_DOME_ACE_TUCKER        = 83;
const TRAINER_PIC_PALACE_MAVEN_SPENSER   = 84;
const TRAINER_PIC_ARENA_TYCOON_GRETA     = 85;
const TRAINER_PIC_FACTORY_HEAD_NOLAND    = 86;
const TRAINER_PIC_PIKE_QUEEN_LUCY        = 87;
const TRAINER_PIC_PYRAMID_KING_BRANDON   = 88;
const TRAINER_PIC_RED                    = 89;
const TRAINER_PIC_LEAF                   = 90;
const TRAINER_PIC_RS_BRENDAN             = 91;
const TRAINER_PIC_RS_MAY                 = 92;

/* AI SCRIPTS */
const AI_SCRIPT_CHECK_BAD_MOVE        = (1 << 0);
const AI_SCRIPT_TRY_TO_FAINT          = (1 << 1);
const AI_SCRIPT_CHECK_VIABILITY       = (1 << 2);
const AI_SCRIPT_SETUP_FIRST_TURN      = (1 << 3);
const AI_SCRIPT_RISKY                 = (1 << 4);
const AI_SCRIPT_PREFER_POWER_EXTREMES = (1 << 5);
const AI_SCRIPT_PREFER_BATON_PASS     = (1 << 6);
const AI_SCRIPT_DOUBLE_BATTLE         = (1 << 7);
const AI_SCRIPT_HP_AWARE              = (1 << 8);
const AI_SCRIPT_TRY_SUNNY_DAY_START   = (1 << 9);
const AI_SCRIPT_ROAMING               = (1 << 29);
const AI_SCRIPT_SAFARI                = (1 << 30);
const AI_SCRIPT_FIRST_BATTLE          = (1 << 31);

/* HELD ITEMS */
const ITEM_CHERI_BERRY   = 133;
const ITEM_CHESTO_BERRY  = 134;
const ITEM_PECHA_BERRY   = 135;
const ITEM_RAWST_BERRY   = 136;
const ITEM_ASPEAR_BERRY  = 137;
const ITEM_LEPPA_BERRY   = 138;
const ITEM_ORAN_BERRY    = 139;
const ITEM_PERSIM_BERRY  = 140;
const ITEM_LUM_BERRY     = 141;
const ITEM_SITRUS_BERRY  = 142;
const ITEM_FIGY_BERRY    = 143;
const ITEM_WIKI_BERRY    = 144;
const ITEM_MAGO_BERRY    = 145;
const ITEM_AGUAV_BERRY   = 146;
const ITEM_IAPAPA_BERRY  = 147;
const ITEM_RAZZ_BERRY    = 148;
const ITEM_BLUK_BERRY    = 149;
const ITEM_NANAB_BERRY   = 150;
const ITEM_WEPEAR_BERRY  = 151;
const ITEM_PINAP_BERRY   = 152;
const ITEM_POMEG_BERRY   = 153;
const ITEM_KELPSY_BERRY  = 154;
const ITEM_QUALOT_BERRY  = 155;
const ITEM_HONDEW_BERRY  = 156;
const ITEM_GREPA_BERRY   = 157;
const ITEM_TAMATO_BERRY  = 158;
const ITEM_CORNN_BERRY   = 159;
const ITEM_MAGOST_BERRY  = 160;
const ITEM_RABUTA_BERRY  = 161;
const ITEM_NOMEL_BERRY   = 162;
const ITEM_SPELON_BERRY  = 163;
const ITEM_PAMTRE_BERRY  = 164;
const ITEM_WATMEL_BERRY  = 165;
const ITEM_DURIN_BERRY   = 166;
const ITEM_BELUE_BERRY   = 167;
const ITEM_LIECHI_BERRY  = 168;
const ITEM_GANLON_BERRY  = 169;
const ITEM_SALAC_BERRY   = 170;
const ITEM_PETAYA_BERRY  = 171;
const ITEM_APICOT_BERRY  = 172;
const ITEM_LANSAT_BERRY  = 173;
const ITEM_STARF_BERRY   = 174;
const ITEM_ENIGMA_BERRY  = 175;

const ITEM_BRIGHT_POWDER  = 179;
const ITEM_WHITE_HERB     = 180;
const ITEM_MACHO_BRACE    = 181;
const ITEM_EXP_SHARE      = 182;
const ITEM_QUICK_CLAW     = 183;
const ITEM_SOOTHE_BELL    = 184;
const ITEM_MENTAL_HERB    = 185;
const ITEM_CHOICE_BAND    = 186;
const ITEM_KINGS_ROCK     = 187;
const ITEM_SILVER_POWDER  = 188;
const ITEM_AMULET_COIN    = 189;
const ITEM_CLEANSE_TAG    = 190;
const ITEM_SOUL_DEW       = 191;
const ITEM_DEEP_SEA_TOOTH = 192;
const ITEM_DEEP_SEA_SCALE = 193;
const ITEM_SMOKE_BALL     = 194;
const ITEM_EVERSTONE      = 195;
const ITEM_FOCUS_BAND     = 196;
const ITEM_LUCKY_EGG      = 197;
const ITEM_SCOPE_LENS     = 198;
const ITEM_METAL_COAT     = 199;
const ITEM_LEFTOVERS      = 200;
const ITEM_DRAGON_SCALE   = 201;
const ITEM_LIGHT_BALL     = 202;
const ITEM_SOFT_SAND      = 203;
const ITEM_HARD_STONE     = 204;
const ITEM_MIRACLE_SEED   = 205;
const ITEM_BLACK_GLASSES  = 206;
const ITEM_BLACK_BELT     = 207;
const ITEM_MAGNET         = 208;
const ITEM_MYSTIC_WATER   = 209;
const ITEM_SHARP_BEAK     = 210;
const ITEM_POISON_BARB    = 211;
const ITEM_NEVER_MELT_ICE = 212;
const ITEM_SPELL_TAG      = 213;
const ITEM_TWISTED_SPOON  = 214;
const ITEM_CHARCOAL       = 215;
const ITEM_DRAGON_FANG    = 216;
const ITEM_SILK_SCARF     = 217;
const ITEM_UP_GRADE       = 218;
const ITEM_SHELL_BELL     = 219;
const ITEM_SEA_INCENSE    = 220;
const ITEM_LAX_INCENSE    = 221;
const ITEM_LUCKY_PUNCH    = 222;
const ITEM_METAL_POWDER   = 223;
const ITEM_THICK_CLUB     = 224;
const ITEM_STICK          = 225;

/* SPECIES */
// TODO: species is used here and in gift egg. This should be split into a separate import
const SPECIES_NONE        = 0;
const SPECIES_BULBASAUR   = 1;
const SPECIES_IVYSAUR     = 2;
const SPECIES_VENUSAUR    = 3;
const SPECIES_CHARMANDER  = 4;
const SPECIES_CHARMELEON  = 5;
const SPECIES_CHARIZARD   = 6;
const SPECIES_SQUIRTLE    = 7;
const SPECIES_WARTORTLE   = 8;
const SPECIES_BLASTOISE   = 9;
const SPECIES_CATERPIE    = 10;
const SPECIES_METAPOD     = 11;
const SPECIES_BUTTERFREE  = 12;
const SPECIES_WEEDLE      = 13;
const SPECIES_KAKUNA      = 14;
const SPECIES_BEEDRILL    = 15;
const SPECIES_PIDGEY      = 16;
const SPECIES_PIDGEOTTO   = 17;
const SPECIES_PIDGEOT     = 18;
const SPECIES_RATTATA     = 19;
const SPECIES_RATICATE    = 20;
const SPECIES_SPEAROW     = 21;
const SPECIES_FEAROW      = 22;
const SPECIES_EKANS       = 23;
const SPECIES_ARBOK       = 24;
const SPECIES_PIKACHU     = 25;
const SPECIES_RAICHU      = 26;
const SPECIES_SANDSHREW   = 27;
const SPECIES_SANDSLASH   = 28;
const SPECIES_NIDORAN_F   = 29;
const SPECIES_NIDORINA    = 30;
const SPECIES_NIDOQUEEN   = 31;
const SPECIES_NIDORAN_M   = 32;
const SPECIES_NIDORINO    = 33;
const SPECIES_NIDOKING    = 34;
const SPECIES_CLEFAIRY    = 35;
const SPECIES_CLEFABLE    = 36;
const SPECIES_VULPIX      = 37;
const SPECIES_NINETALES   = 38;
const SPECIES_JIGGLYPUFF  = 39;
const SPECIES_WIGGLYTUFF  = 40;
const SPECIES_ZUBAT       = 41;
const SPECIES_GOLBAT      = 42;
const SPECIES_ODDISH      = 43;
const SPECIES_GLOOM       = 44;
const SPECIES_VILEPLUME   = 45;
const SPECIES_PARAS       = 46;
const SPECIES_PARASECT    = 47;
const SPECIES_VENONAT     = 48;
const SPECIES_VENOMOTH    = 49;
const SPECIES_DIGLETT     = 50;
const SPECIES_DUGTRIO     = 51;
const SPECIES_MEOWTH      = 52;
const SPECIES_PERSIAN     = 53;
const SPECIES_PSYDUCK     = 54;
const SPECIES_GOLDUCK     = 55;
const SPECIES_MANKEY      = 56;
const SPECIES_PRIMEAPE    = 57;
const SPECIES_GROWLITHE   = 58;
const SPECIES_ARCANINE    = 59;
const SPECIES_POLIWAG     = 60;
const SPECIES_POLIWHIRL   = 61;
const SPECIES_POLIWRATH   = 62;
const SPECIES_ABRA        = 63;
const SPECIES_KADABRA     = 64;
const SPECIES_ALAKAZAM    = 65;
const SPECIES_MACHOP      = 66;
const SPECIES_MACHOKE     = 67;
const SPECIES_MACHAMP     = 68;
const SPECIES_BELLSPROUT  = 69;
const SPECIES_WEEPINBELL  = 70;
const SPECIES_VICTREEBEL  = 71;
const SPECIES_TENTACOOL   = 72;
const SPECIES_TENTACRUEL  = 73;
const SPECIES_GEODUDE     = 74;
const SPECIES_GRAVELER    = 75;
const SPECIES_GOLEM       = 76;
const SPECIES_PONYTA      = 77;
const SPECIES_RAPIDASH    = 78;
const SPECIES_SLOWPOKE    = 79;
const SPECIES_SLOWBRO     = 80;
const SPECIES_MAGNEMITE   = 81;
const SPECIES_MAGNETON    = 82;
const SPECIES_FARFETCHD   = 83;
const SPECIES_DODUO       = 84;
const SPECIES_DODRIO      = 85;
const SPECIES_SEEL        = 86;
const SPECIES_DEWGONG     = 87;
const SPECIES_GRIMER      = 88;
const SPECIES_MUK         = 89;
const SPECIES_SHELLDER    = 90;
const SPECIES_CLOYSTER    = 91;
const SPECIES_GASTLY      = 92;
const SPECIES_HAUNTER     = 93;
const SPECIES_GENGAR      = 94;
const SPECIES_ONIX        = 95;
const SPECIES_DROWZEE     = 96;
const SPECIES_HYPNO       = 97;
const SPECIES_KRABBY      = 98;
const SPECIES_KINGLER     = 99;
const SPECIES_VOLTORB     = 100;
const SPECIES_ELECTRODE   = 101;
const SPECIES_EXEGGCUTE   = 102;
const SPECIES_EXEGGUTOR   = 103;
const SPECIES_CUBONE      = 104;
const SPECIES_MAROWAK     = 105;
const SPECIES_HITMONLEE   = 106;
const SPECIES_HITMONCHAN  = 107;
const SPECIES_LICKITUNG   = 108;
const SPECIES_KOFFING     = 109;
const SPECIES_WEEZING     = 110;
const SPECIES_RHYHORN     = 111;
const SPECIES_RHYDON      = 112;
const SPECIES_CHANSEY     = 113;
const SPECIES_TANGELA     = 114;
const SPECIES_KANGASKHAN  = 115;
const SPECIES_HORSEA      = 116;
const SPECIES_SEADRA      = 117;
const SPECIES_GOLDEEN     = 118;
const SPECIES_SEAKING     = 119;
const SPECIES_STARYU      = 120;
const SPECIES_STARMIE     = 121;
const SPECIES_MR_MIME     = 122;
const SPECIES_SCYTHER     = 123;
const SPECIES_JYNX        = 124;
const SPECIES_ELECTABUZZ  = 125;
const SPECIES_MAGMAR      = 126;
const SPECIES_PINSIR      = 127;
const SPECIES_TAUROS      = 128;
const SPECIES_MAGIKARP    = 129;
const SPECIES_GYARADOS    = 130;
const SPECIES_LAPRAS      = 131;
const SPECIES_DITTO       = 132;
const SPECIES_EEVEE       = 133;
const SPECIES_VAPOREON    = 134;
const SPECIES_JOLTEON     = 135;
const SPECIES_FLAREON     = 136;
const SPECIES_PORYGON     = 137;
const SPECIES_OMANYTE     = 138;
const SPECIES_OMASTAR     = 139;
const SPECIES_KABUTO      = 140;
const SPECIES_KABUTOPS    = 141;
const SPECIES_AERODACTYL  = 142;
const SPECIES_SNORLAX     = 143;
const SPECIES_ARTICUNO    = 144;
const SPECIES_ZAPDOS      = 145;
const SPECIES_MOLTRES     = 146;
const SPECIES_DRATINI     = 147;
const SPECIES_DRAGONAIR   = 148;
const SPECIES_DRAGONITE   = 149;
const SPECIES_MEWTWO      = 150;
const SPECIES_MEW         = 151;
const SPECIES_CHIKORITA   = 152;
const SPECIES_BAYLEEF     = 153;
const SPECIES_MEGANIUM    = 154;
const SPECIES_CYNDAQUIL   = 155;
const SPECIES_QUILAVA     = 156;
const SPECIES_TYPHLOSION  = 157;
const SPECIES_TOTODILE    = 158;
const SPECIES_CROCONAW    = 159;
const SPECIES_FERALIGATR  = 160;
const SPECIES_SENTRET     = 161;
const SPECIES_FURRET      = 162;
const SPECIES_HOOTHOOT    = 163;
const SPECIES_NOCTOWL     = 164;
const SPECIES_LEDYBA      = 165;
const SPECIES_LEDIAN      = 166;
const SPECIES_SPINARAK    = 167;
const SPECIES_ARIADOS     = 168;
const SPECIES_CROBAT      = 169;
const SPECIES_CHINCHOU    = 170;
const SPECIES_LANTURN     = 171;
const SPECIES_PICHU       = 172;
const SPECIES_CLEFFA      = 173;
const SPECIES_IGGLYBUFF   = 174;
const SPECIES_TOGEPI      = 175;
const SPECIES_TOGETIC     = 176;
const SPECIES_NATU        = 177;
const SPECIES_XATU        = 178;
const SPECIES_MAREEP      = 179;
const SPECIES_FLAAFFY     = 180;
const SPECIES_AMPHAROS    = 181;
const SPECIES_BELLOSSOM   = 182;
const SPECIES_MARILL      = 183;
const SPECIES_AZUMARILL   = 184;
const SPECIES_SUDOWOODO   = 185;
const SPECIES_POLITOED    = 186;
const SPECIES_HOPPIP      = 187;
const SPECIES_SKIPLOOM    = 188;
const SPECIES_JUMPLUFF    = 189;
const SPECIES_AIPOM       = 190;
const SPECIES_SUNKERN     = 191;
const SPECIES_SUNFLORA    = 192;
const SPECIES_YANMA       = 193;
const SPECIES_WOOPER      = 194;
const SPECIES_QUAGSIRE    = 195;
const SPECIES_ESPEON      = 196;
const SPECIES_UMBREON     = 197;
const SPECIES_MURKROW     = 198;
const SPECIES_SLOWKING    = 199;
const SPECIES_MISDREAVUS  = 200;
const SPECIES_UNOWN       = 201;
const SPECIES_WOBBUFFET   = 202;
const SPECIES_GIRAFARIG   = 203;
const SPECIES_PINECO      = 204;
const SPECIES_FORRETRESS  = 205;
const SPECIES_DUNSPARCE   = 206;
const SPECIES_GLIGAR      = 207;
const SPECIES_STEELIX     = 208;
const SPECIES_SNUBBULL    = 209;
const SPECIES_GRANBULL    = 210;
const SPECIES_QWILFISH    = 211;
const SPECIES_SCIZOR      = 212;
const SPECIES_SHUCKLE     = 213;
const SPECIES_HERACROSS   = 214;
const SPECIES_SNEASEL     = 215;
const SPECIES_TEDDIURSA   = 216;
const SPECIES_URSARING    = 217;
const SPECIES_SLUGMA      = 218;
const SPECIES_MAGCARGO    = 219;
const SPECIES_SWINUB      = 220;
const SPECIES_PILOSWINE   = 221;
const SPECIES_CORSOLA     = 222;
const SPECIES_REMORAID    = 223;
const SPECIES_OCTILLERY   = 224;
const SPECIES_DELIBIRD    = 225;
const SPECIES_MANTINE     = 226;
const SPECIES_SKARMORY    = 227;
const SPECIES_HOUNDOUR    = 228;
const SPECIES_HOUNDOOM    = 229;
const SPECIES_KINGDRA     = 230;
const SPECIES_PHANPY      = 231;
const SPECIES_DONPHAN     = 232;
const SPECIES_PORYGON2    = 233;
const SPECIES_STANTLER    = 234;
const SPECIES_SMEARGLE    = 235;
const SPECIES_TYROGUE     = 236;
const SPECIES_HITMONTOP   = 237;
const SPECIES_SMOOCHUM    = 238;
const SPECIES_ELEKID      = 239;
const SPECIES_MAGBY       = 240;
const SPECIES_MILTANK     = 241;
const SPECIES_BLISSEY     = 242;
const SPECIES_RAIKOU      = 243;
const SPECIES_ENTEI       = 244;
const SPECIES_SUICUNE     = 245;
const SPECIES_LARVITAR    = 246;
const SPECIES_PUPITAR     = 247;
const SPECIES_TYRANITAR   = 248;
const SPECIES_LUGIA       = 249;
const SPECIES_HO_OH       = 250;
const SPECIES_CELEBI      = 251;
const SPECIES_OLD_UNOWN_B = 252;
const SPECIES_OLD_UNOWN_C = 253;
const SPECIES_OLD_UNOWN_D = 254;
const SPECIES_OLD_UNOWN_E = 255;
const SPECIES_OLD_UNOWN_F = 256;
const SPECIES_OLD_UNOWN_G = 257;
const SPECIES_OLD_UNOWN_H = 258;
const SPECIES_OLD_UNOWN_I = 259;
const SPECIES_OLD_UNOWN_J = 260;
const SPECIES_OLD_UNOWN_K = 261;
const SPECIES_OLD_UNOWN_L = 262;
const SPECIES_OLD_UNOWN_M = 263;
const SPECIES_OLD_UNOWN_N = 264;
const SPECIES_OLD_UNOWN_O = 265;
const SPECIES_OLD_UNOWN_P = 266;
const SPECIES_OLD_UNOWN_Q = 267;
const SPECIES_OLD_UNOWN_R = 268;
const SPECIES_OLD_UNOWN_S = 269;
const SPECIES_OLD_UNOWN_T = 270;
const SPECIES_OLD_UNOWN_U = 271;
const SPECIES_OLD_UNOWN_V = 272;
const SPECIES_OLD_UNOWN_W = 273;
const SPECIES_OLD_UNOWN_X = 274;
const SPECIES_OLD_UNOWN_Y = 275;
const SPECIES_OLD_UNOWN_Z = 276;
const SPECIES_TREECKO     = 277;
const SPECIES_GROVYLE     = 278;
const SPECIES_SCEPTILE    = 279;
const SPECIES_TORCHIC     = 280;
const SPECIES_COMBUSKEN   = 281;
const SPECIES_BLAZIKEN    = 282;
const SPECIES_MUDKIP      = 283;
const SPECIES_MARSHTOMP   = 284;
const SPECIES_SWAMPERT    = 285;
const SPECIES_POOCHYENA   = 286;
const SPECIES_MIGHTYENA   = 287;
const SPECIES_ZIGZAGOON   = 288;
const SPECIES_LINOONE     = 289;
const SPECIES_WURMPLE     = 290;
const SPECIES_SILCOON     = 291;
const SPECIES_BEAUTIFLY   = 292;
const SPECIES_CASCOON     = 293;
const SPECIES_DUSTOX      = 294;
const SPECIES_LOTAD       = 295;
const SPECIES_LOMBRE      = 296;
const SPECIES_LUDICOLO    = 297;
const SPECIES_SEEDOT      = 298;
const SPECIES_NUZLEAF     = 299;
const SPECIES_SHIFTRY     = 300;
const SPECIES_NINCADA     = 301;
const SPECIES_NINJASK     = 302;
const SPECIES_SHEDINJA    = 303;
const SPECIES_TAILLOW     = 304;
const SPECIES_SWELLOW     = 305;
const SPECIES_SHROOMISH   = 306;
const SPECIES_BRELOOM     = 307;
const SPECIES_SPINDA      = 308;
const SPECIES_WINGULL     = 309;
const SPECIES_PELIPPER    = 310;
const SPECIES_SURSKIT     = 311;
const SPECIES_MASQUERAIN  = 312;
const SPECIES_WAILMER     = 313;
const SPECIES_WAILORD     = 314;
const SPECIES_SKITTY      = 315;
const SPECIES_DELCATTY    = 316;
const SPECIES_KECLEON     = 317;
const SPECIES_BALTOY      = 318;
const SPECIES_CLAYDOL     = 319;
const SPECIES_NOSEPASS    = 320;
const SPECIES_TORKOAL     = 321;
const SPECIES_SABLEYE     = 322;
const SPECIES_BARBOACH    = 323;
const SPECIES_WHISCASH    = 324;
const SPECIES_LUVDISC     = 325;
const SPECIES_CORPHISH    = 326;
const SPECIES_CRAWDAUNT   = 327;
const SPECIES_FEEBAS      = 328;
const SPECIES_MILOTIC     = 329;
const SPECIES_CARVANHA    = 330;
const SPECIES_SHARPEDO    = 331;
const SPECIES_TRAPINCH    = 332;
const SPECIES_VIBRAVA     = 333;
const SPECIES_FLYGON      = 334;
const SPECIES_MAKUHITA    = 335;
const SPECIES_HARIYAMA    = 336;
const SPECIES_ELECTRIKE   = 337;
const SPECIES_MANECTRIC   = 338;
const SPECIES_NUMEL       = 339;
const SPECIES_CAMERUPT    = 340;
const SPECIES_SPHEAL      = 341;
const SPECIES_SEALEO      = 342;
const SPECIES_WALREIN     = 343;
const SPECIES_CACNEA      = 344;
const SPECIES_CACTURNE    = 345;
const SPECIES_SNORUNT     = 346;
const SPECIES_GLALIE      = 347;
const SPECIES_LUNATONE    = 348;
const SPECIES_SOLROCK     = 349;
const SPECIES_AZURILL     = 350;
const SPECIES_SPOINK      = 351;
const SPECIES_GRUMPIG     = 352;
const SPECIES_PLUSLE      = 353;
const SPECIES_MINUN       = 354;
const SPECIES_MAWILE      = 355;
const SPECIES_MEDITITE    = 356;
const SPECIES_MEDICHAM    = 357;
const SPECIES_SWABLU      = 358;
const SPECIES_ALTARIA     = 359;
const SPECIES_WYNAUT      = 360;
const SPECIES_DUSKULL     = 361;
const SPECIES_DUSCLOPS    = 362;
const SPECIES_ROSELIA     = 363;
const SPECIES_SLAKOTH     = 364;
const SPECIES_VIGOROTH    = 365;
const SPECIES_SLAKING     = 366;
const SPECIES_GULPIN      = 367;
const SPECIES_SWALOT      = 368;
const SPECIES_TROPIUS     = 369;
const SPECIES_WHISMUR     = 370;
const SPECIES_LOUDRED     = 371;
const SPECIES_EXPLOUD     = 372;
const SPECIES_CLAMPERL    = 373;
const SPECIES_HUNTAIL     = 374;
const SPECIES_GOREBYSS    = 375;
const SPECIES_ABSOL       = 376;
const SPECIES_SHUPPET     = 377;
const SPECIES_BANETTE     = 378;
const SPECIES_SEVIPER     = 379;
const SPECIES_ZANGOOSE    = 380;
const SPECIES_RELICANTH   = 381;
const SPECIES_ARON        = 382;
const SPECIES_LAIRON      = 383;
const SPECIES_AGGRON      = 384;
const SPECIES_CASTFORM    = 385;
const SPECIES_VOLBEAT     = 386;
const SPECIES_ILLUMISE    = 387;
const SPECIES_LILEEP      = 388;
const SPECIES_CRADILY     = 389;
const SPECIES_ANORITH     = 390;
const SPECIES_ARMALDO     = 391;
const SPECIES_RALTS       = 392;
const SPECIES_KIRLIA      = 393;
const SPECIES_GARDEVOIR   = 394;
const SPECIES_BAGON       = 395;
const SPECIES_SHELGON     = 396;
const SPECIES_SALAMENCE   = 397;
const SPECIES_BELDUM      = 398;
const SPECIES_METANG      = 399;
const SPECIES_METAGROSS   = 400;
const SPECIES_REGIROCK    = 401;
const SPECIES_REGICE      = 402;
const SPECIES_REGISTEEL   = 403;
const SPECIES_KYOGRE      = 404;
const SPECIES_GROUDON     = 405;
const SPECIES_RAYQUAZA    = 406;
const SPECIES_LATIAS      = 407;
const SPECIES_LATIOS      = 408;
const SPECIES_JIRACHI     = 409;
const SPECIES_DEOXYS      = 410;
const SPECIES_CHIMECHO    = 411;
const SPECIES_EGG         = 412;


const speciesNames = new Map();

speciesNames.set(0  , "NONE");
speciesNames.set(1  , "BULBASAUR");
speciesNames.set(2  , "IVYSAUR");
speciesNames.set(3  , "VENUSAUR");
speciesNames.set(4  , "CHARMANDER");
speciesNames.set(5  , "CHARMELEON");
speciesNames.set(6  , "CHARIZARD");
speciesNames.set(7  , "SQUIRTLE");
speciesNames.set(8  , "WARTORTLE");
speciesNames.set(9  , "BLASTOISE");
speciesNames.set(10 , "CATERPIE");
speciesNames.set(11 , "METAPOD");
speciesNames.set(12 , "BUTTERFREE");
speciesNames.set(13 , "WEEDLE");
speciesNames.set(14 , "KAKUNA");
speciesNames.set(15 , "BEEDRILL");
speciesNames.set(16 , "PIDGEY");
speciesNames.set(17 , "PIDGEOTTO");
speciesNames.set(18 , "PIDGEOT");
speciesNames.set(19 , "RATTATA");
speciesNames.set(20 , "RATICATE");
speciesNames.set(21 , "SPEAROW");
speciesNames.set(22 , "FEAROW");
speciesNames.set(23 , "EKANS");
speciesNames.set(24 , "ARBOK");
speciesNames.set(25 , "PIKACHU");
speciesNames.set(26 , "RAICHU");
speciesNames.set(27 , "SANDSHREW");
speciesNames.set(28 , "SANDSLASH");
speciesNames.set(29 , "NIDORAN_F");
speciesNames.set(30 , "NIDORINA");
speciesNames.set(31 , "NIDOQUEEN");
speciesNames.set(32 , "NIDORAN_M");
speciesNames.set(33 , "NIDORINO");
speciesNames.set(34 , "NIDOKING");
speciesNames.set(35 , "CLEFAIRY");
speciesNames.set(36 , "CLEFABLE");
speciesNames.set(37 , "VULPIX");
speciesNames.set(38 , "NINETALES");
speciesNames.set(39 , "JIGGLYPUFF");
speciesNames.set(40 , "WIGGLYTUFF");
speciesNames.set(41 , "ZUBAT");
speciesNames.set(42 , "GOLBAT");
speciesNames.set(43 , "ODDISH");
speciesNames.set(44 , "GLOOM");
speciesNames.set(45 , "VILEPLUME");
speciesNames.set(46 , "PARAS");
speciesNames.set(47 , "PARASECT");
speciesNames.set(48 , "VENONAT");
speciesNames.set(49 , "VENOMOTH");
speciesNames.set(50 , "DIGLETT");
speciesNames.set(51 , "DUGTRIO");
speciesNames.set(52 , "MEOWTH");
speciesNames.set(53 , "PERSIAN");
speciesNames.set(54 , "PSYDUCK");
speciesNames.set(55 , "GOLDUCK");
speciesNames.set(56 , "MANKEY");
speciesNames.set(57 , "PRIMEAPE");
speciesNames.set(58 , "GROWLITHE");
speciesNames.set(59 , "ARCANINE");
speciesNames.set(60 , "POLIWAG");
speciesNames.set(61 , "POLIWHIRL");
speciesNames.set(62 , "POLIWRATH");
speciesNames.set(63 , "ABRA");
speciesNames.set(64 , "KADABRA");
speciesNames.set(65 , "ALAKAZAM");
speciesNames.set(66 , "MACHOP");
speciesNames.set(67 , "MACHOKE");
speciesNames.set(68 , "MACHAMP");
speciesNames.set(69 , "BELLSPROUT");
speciesNames.set(70 , "WEEPINBELL");
speciesNames.set(71 , "VICTREEBEL");
speciesNames.set(72 , "TENTACOOL");
speciesNames.set(73 , "TENTACRUEL");
speciesNames.set(74 , "GEODUDE");
speciesNames.set(75 , "GRAVELER");
speciesNames.set(76 , "GOLEM");
speciesNames.set(77 , "PONYTA");
speciesNames.set(78 , "RAPIDASH");
speciesNames.set(79 , "SLOWPOKE");
speciesNames.set(80 , "SLOWBRO");
speciesNames.set(81 , "MAGNEMITE");
speciesNames.set(82 , "MAGNETON");
speciesNames.set(83 , "FARFETCHD");
speciesNames.set(84 , "DODUO");
speciesNames.set(85 , "DODRIO");
speciesNames.set(86 , "SEEL");
speciesNames.set(87 , "DEWGONG");
speciesNames.set(88 , "GRIMER");
speciesNames.set(89 , "MUK");
speciesNames.set(90 , "SHELLDER");
speciesNames.set(91 , "CLOYSTER");
speciesNames.set(92 , "GASTLY");
speciesNames.set(93 , "HAUNTER");
speciesNames.set(94 , "GENGAR");
speciesNames.set(95 , "ONIX");
speciesNames.set(96 , "DROWZEE");
speciesNames.set(97 , "HYPNO");
speciesNames.set(98 , "KRABBY");
speciesNames.set(99 , "KINGLER");
speciesNames.set(100, "VOLTORB");
speciesNames.set(101, "ELECTRODE");
speciesNames.set(102, "EXEGGCUTE");
speciesNames.set(103, "EXEGGUTOR");
speciesNames.set(104, "CUBONE");
speciesNames.set(105, "MAROWAK");
speciesNames.set(106, "HITMONLEE");
speciesNames.set(107, "HITMONCHAN");
speciesNames.set(108, "LICKITUNG");
speciesNames.set(109, "KOFFING");
speciesNames.set(110, "WEEZING");
speciesNames.set(111, "RHYHORN");
speciesNames.set(112, "RHYDON");
speciesNames.set(113, "CHANSEY");
speciesNames.set(114, "TANGELA");
speciesNames.set(115, "KANGASKHAN");
speciesNames.set(116, "HORSEA");
speciesNames.set(117, "SEADRA");
speciesNames.set(118, "GOLDEEN");
speciesNames.set(119, "SEAKING");
speciesNames.set(120, "STARYU");
speciesNames.set(121, "STARMIE");
speciesNames.set(122, "MR_MIME");
speciesNames.set(123, "SCYTHER");
speciesNames.set(124, "JYNX");
speciesNames.set(125, "ELECTABUZZ");
speciesNames.set(126, "MAGMAR");
speciesNames.set(127, "PINSIR");
speciesNames.set(128, "TAUROS");
speciesNames.set(129, "MAGIKARP");
speciesNames.set(130, "GYARADOS");
speciesNames.set(131, "LAPRAS");
speciesNames.set(132, "DITTO");
speciesNames.set(133, "EEVEE");
speciesNames.set(134, "VAPOREON");
speciesNames.set(135, "JOLTEON");
speciesNames.set(136, "FLAREON");
speciesNames.set(137, "PORYGON");
speciesNames.set(138, "OMANYTE");
speciesNames.set(139, "OMASTAR");
speciesNames.set(140, "KABUTO");
speciesNames.set(141, "KABUTOPS");
speciesNames.set(142, "AERODACTYL");
speciesNames.set(143, "SNORLAX");
speciesNames.set(144, "ARTICUNO");
speciesNames.set(145, "ZAPDOS");
speciesNames.set(146, "MOLTRES");
speciesNames.set(147, "DRATINI");
speciesNames.set(148, "DRAGONAIR");
speciesNames.set(149, "DRAGONITE");
speciesNames.set(150, "MEWTWO");
speciesNames.set(151, "MEW");
speciesNames.set(152, "CHIKORITA");
speciesNames.set(153, "BAYLEEF");
speciesNames.set(154, "MEGANIUM");
speciesNames.set(155, "CYNDAQUIL");
speciesNames.set(156, "QUILAVA");
speciesNames.set(157, "TYPHLOSION");
speciesNames.set(158, "TOTODILE");
speciesNames.set(159, "CROCONAW");
speciesNames.set(160, "FERALIGATR");
speciesNames.set(161, "SENTRET");
speciesNames.set(162, "FURRET");
speciesNames.set(163, "HOOTHOOT");
speciesNames.set(164, "NOCTOWL");
speciesNames.set(165, "LEDYBA");
speciesNames.set(166, "LEDIAN");
speciesNames.set(167, "SPINARAK");
speciesNames.set(168, "ARIADOS");
speciesNames.set(169, "CROBAT");
speciesNames.set(170, "CHINCHOU");
speciesNames.set(171, "LANTURN");
speciesNames.set(172, "PICHU");
speciesNames.set(173, "CLEFFA");
speciesNames.set(174, "IGGLYBUFF");
speciesNames.set(175, "TOGEPI");
speciesNames.set(176, "TOGETIC");
speciesNames.set(177, "NATU");
speciesNames.set(178, "XATU");
speciesNames.set(179, "MAREEP");
speciesNames.set(180, "FLAAFFY");
speciesNames.set(181, "AMPHAROS");
speciesNames.set(182, "BELLOSSOM");
speciesNames.set(183, "MARILL");
speciesNames.set(184, "AZUMARILL");
speciesNames.set(185, "SUDOWOODO");
speciesNames.set(186, "POLITOED");
speciesNames.set(187, "HOPPIP");
speciesNames.set(188, "SKIPLOOM");
speciesNames.set(189, "JUMPLUFF");
speciesNames.set(190, "AIPOM");
speciesNames.set(191, "SUNKERN");
speciesNames.set(192, "SUNFLORA");
speciesNames.set(193, "YANMA");
speciesNames.set(194, "WOOPER");
speciesNames.set(195, "QUAGSIRE");
speciesNames.set(196, "ESPEON");
speciesNames.set(197, "UMBREON");
speciesNames.set(198, "MURKROW");
speciesNames.set(199, "SLOWKING");
speciesNames.set(200, "MISDREAVUS");
speciesNames.set(201, "UNOWN");
speciesNames.set(202, "WOBBUFFET");
speciesNames.set(203, "GIRAFARIG");
speciesNames.set(204, "PINECO");
speciesNames.set(205, "FORRETRESS");
speciesNames.set(206, "DUNSPARCE");
speciesNames.set(207, "GLIGAR");
speciesNames.set(208, "STEELIX");
speciesNames.set(209, "SNUBBULL");
speciesNames.set(210, "GRANBULL");
speciesNames.set(211, "QWILFISH");
speciesNames.set(212, "SCIZOR");
speciesNames.set(213, "SHUCKLE");
speciesNames.set(214, "HERACROSS");
speciesNames.set(215, "SNEASEL");
speciesNames.set(216, "TEDDIURSA");
speciesNames.set(217, "URSARING");
speciesNames.set(218, "SLUGMA");
speciesNames.set(219, "MAGCARGO");
speciesNames.set(220, "SWINUB");
speciesNames.set(221, "PILOSWINE");
speciesNames.set(222, "CORSOLA");
speciesNames.set(223, "REMORAID");
speciesNames.set(224, "OCTILLERY");
speciesNames.set(225, "DELIBIRD");
speciesNames.set(226, "MANTINE");
speciesNames.set(227, "SKARMORY");
speciesNames.set(228, "HOUNDOUR");
speciesNames.set(229, "HOUNDOOM");
speciesNames.set(230, "KINGDRA");
speciesNames.set(231, "PHANPY");
speciesNames.set(232, "DONPHAN");
speciesNames.set(233, "PORYGON2");
speciesNames.set(234, "STANTLER");
speciesNames.set(235, "SMEARGLE");
speciesNames.set(236, "TYROGUE");
speciesNames.set(237, "HITMONTOP");
speciesNames.set(238, "SMOOCHUM");
speciesNames.set(239, "ELEKID");
speciesNames.set(240, "MAGBY");
speciesNames.set(241, "MILTANK");
speciesNames.set(242, "BLISSEY");
speciesNames.set(243, "RAIKOU");
speciesNames.set(244, "ENTEI");
speciesNames.set(245, "SUICUNE");
speciesNames.set(246, "LARVITAR");
speciesNames.set(247, "PUPITAR");
speciesNames.set(248, "TYRANITAR");
speciesNames.set(249, "LUGIA");
speciesNames.set(250, "HO_OH");
speciesNames.set(251, "CELEBI");
speciesNames.set(252, "OLD_UNOWN_B");
speciesNames.set(253, "OLD_UNOWN_C");
speciesNames.set(254, "OLD_UNOWN_D");
speciesNames.set(255, "OLD_UNOWN_E");
speciesNames.set(256, "OLD_UNOWN_F");
speciesNames.set(257, "OLD_UNOWN_G");
speciesNames.set(258, "OLD_UNOWN_H");
speciesNames.set(259, "OLD_UNOWN_I");
speciesNames.set(260, "OLD_UNOWN_J");
speciesNames.set(261, "OLD_UNOWN_K");
speciesNames.set(262, "OLD_UNOWN_L");
speciesNames.set(263, "OLD_UNOWN_M");
speciesNames.set(264, "OLD_UNOWN_N");
speciesNames.set(265, "OLD_UNOWN_O");
speciesNames.set(266, "OLD_UNOWN_P");
speciesNames.set(267, "OLD_UNOWN_Q");
speciesNames.set(268, "OLD_UNOWN_R");
speciesNames.set(269, "OLD_UNOWN_S");
speciesNames.set(270, "OLD_UNOWN_T");
speciesNames.set(271, "OLD_UNOWN_U");
speciesNames.set(272, "OLD_UNOWN_V");
speciesNames.set(273, "OLD_UNOWN_W");
speciesNames.set(274, "OLD_UNOWN_X");
speciesNames.set(275, "OLD_UNOWN_Y");
speciesNames.set(276, "OLD_UNOWN_Z");
speciesNames.set(277, "TREECKO");
speciesNames.set(278, "GROVYLE");
speciesNames.set(279, "SCEPTILE");
speciesNames.set(280, "TORCHIC");
speciesNames.set(281, "COMBUSKEN");
speciesNames.set(282, "BLAZIKEN");
speciesNames.set(283, "MUDKIP");
speciesNames.set(284, "MARSHTOMP");
speciesNames.set(285, "SWAMPERT");
speciesNames.set(286, "POOCHYENA");
speciesNames.set(287, "MIGHTYENA");
speciesNames.set(288, "ZIGZAGOON");
speciesNames.set(289, "LINOONE");
speciesNames.set(290, "WURMPLE");
speciesNames.set(291, "SILCOON");
speciesNames.set(292, "BEAUTIFLY");
speciesNames.set(293, "CASCOON");
speciesNames.set(294, "DUSTOX");
speciesNames.set(295, "LOTAD");
speciesNames.set(296, "LOMBRE");
speciesNames.set(297, "LUDICOLO");
speciesNames.set(298, "SEEDOT");
speciesNames.set(299, "NUZLEAF");
speciesNames.set(300, "SHIFTRY");
speciesNames.set(301, "NINCADA");
speciesNames.set(302, "NINJASK");
speciesNames.set(303, "SHEDINJA");
speciesNames.set(304, "TAILLOW");
speciesNames.set(305, "SWELLOW");
speciesNames.set(306, "SHROOMISH");
speciesNames.set(307, "BRELOOM");
speciesNames.set(308, "SPINDA");
speciesNames.set(309, "WINGULL");
speciesNames.set(310, "PELIPPER");
speciesNames.set(311, "SURSKIT");
speciesNames.set(312, "MASQUERAIN");
speciesNames.set(313, "WAILMER");
speciesNames.set(314, "WAILORD");
speciesNames.set(315, "SKITTY");
speciesNames.set(316, "DELCATTY");
speciesNames.set(317, "KECLEON");
speciesNames.set(318, "BALTOY");
speciesNames.set(319, "CLAYDOL");
speciesNames.set(320, "NOSEPASS");
speciesNames.set(321, "TORKOAL");
speciesNames.set(322, "SABLEYE");
speciesNames.set(323, "BARBOACH");
speciesNames.set(324, "WHISCASH");
speciesNames.set(325, "LUVDISC");
speciesNames.set(326, "CORPHISH");
speciesNames.set(327, "CRAWDAUNT");
speciesNames.set(328, "FEEBAS");
speciesNames.set(329, "MILOTIC");
speciesNames.set(330, "CARVANHA");
speciesNames.set(331, "SHARPEDO");
speciesNames.set(332, "TRAPINCH");
speciesNames.set(333, "VIBRAVA");
speciesNames.set(334, "FLYGON");
speciesNames.set(335, "MAKUHITA");
speciesNames.set(336, "HARIYAMA");
speciesNames.set(337, "ELECTRIKE");
speciesNames.set(338, "MANECTRIC");
speciesNames.set(339, "NUMEL");
speciesNames.set(340, "CAMERUPT");
speciesNames.set(341, "SPHEAL");
speciesNames.set(342, "SEALEO");
speciesNames.set(343, "WALREIN");
speciesNames.set(344, "CACNEA");
speciesNames.set(345, "CACTURNE");
speciesNames.set(346, "SNORUNT");
speciesNames.set(347, "GLALIE");
speciesNames.set(348, "LUNATONE");
speciesNames.set(349, "SOLROCK");
speciesNames.set(350, "AZURILL");
speciesNames.set(351, "SPOINK");
speciesNames.set(352, "GRUMPIG");
speciesNames.set(353, "PLUSLE");
speciesNames.set(354, "MINUN");
speciesNames.set(355, "MAWILE");
speciesNames.set(356, "MEDITITE");
speciesNames.set(357, "MEDICHAM");
speciesNames.set(358, "SWABLU");
speciesNames.set(359, "ALTARIA");
speciesNames.set(360, "WYNAUT");
speciesNames.set(361, "DUSKULL");
speciesNames.set(362, "DUSCLOPS");
speciesNames.set(363, "ROSELIA");
speciesNames.set(364, "SLAKOTH");
speciesNames.set(365, "VIGOROTH");
speciesNames.set(366, "SLAKING");
speciesNames.set(367, "GULPIN");
speciesNames.set(368, "SWALOT");
speciesNames.set(369, "TROPIUS");
speciesNames.set(370, "WHISMUR");
speciesNames.set(371, "LOUDRED");
speciesNames.set(372, "EXPLOUD");
speciesNames.set(373, "CLAMPERL");
speciesNames.set(374, "HUNTAIL");
speciesNames.set(375, "GOREBYSS");
speciesNames.set(376, "ABSOL");
speciesNames.set(377, "SHUPPET");
speciesNames.set(378, "BANETTE");
speciesNames.set(379, "SEVIPER");
speciesNames.set(380, "ZANGOOSE");
speciesNames.set(381, "RELICANTH");
speciesNames.set(382, "ARON");
speciesNames.set(383, "LAIRON");
speciesNames.set(384, "AGGRON");
speciesNames.set(385, "CASTFORM");
speciesNames.set(386, "VOLBEAT");
speciesNames.set(387, "ILLUMISE");
speciesNames.set(388, "LILEEP");
speciesNames.set(389, "CRADILY");
speciesNames.set(390, "ANORITH");
speciesNames.set(391, "ARMALDO");
speciesNames.set(392, "RALTS");
speciesNames.set(393, "KIRLIA");
speciesNames.set(394, "GARDEVOIR");
speciesNames.set(395, "BAGON");
speciesNames.set(396, "SHELGON");
speciesNames.set(397, "SALAMENCE");
speciesNames.set(398, "BELDUM");
speciesNames.set(399, "METANG");
speciesNames.set(400, "METAGROSS");
speciesNames.set(401, "REGIROCK");
speciesNames.set(402, "REGICE");
speciesNames.set(403, "REGISTEEL");
speciesNames.set(404, "KYOGRE");
speciesNames.set(405, "GROUDON");
speciesNames.set(406, "RAYQUAZA");
speciesNames.set(407, "LATIAS");
speciesNames.set(408, "LATIOS");
speciesNames.set(409, "JIRACHI");
speciesNames.set(410, "DEOXYS");
speciesNames.set(411, "CHIMECHO");
speciesNames.set(412, "EGG");


/* MOVES */
const MOVE_NONE             = 0;
const MOVE_POUND            = 1;
const MOVE_KARATE_CHOP      = 2;
const MOVE_DOUBLE_SLAP      = 3;
const MOVE_COMET_PUNCH      = 4;
const MOVE_MEGA_PUNCH       = 5;
const MOVE_PAY_DAY          = 6;
const MOVE_FIRE_PUNCH       = 7;
const MOVE_ICE_PUNCH        = 8;
const MOVE_THUNDER_PUNCH    = 9;
const MOVE_SCRATCH          = 10;
const MOVE_VICE_GRIP        = 11;
const MOVE_GUILLOTINE       = 12;
const MOVE_RAZOR_WIND       = 13;
const MOVE_SWORDS_DANCE     = 14;
const MOVE_CUT              = 15;
const MOVE_GUST             = 16;
const MOVE_WING_ATTACK      = 17;
const MOVE_WHIRLWIND        = 18;
const MOVE_FLY              = 19;
const MOVE_BIND             = 20;
const MOVE_SLAM             = 21;
const MOVE_VINE_WHIP        = 22;
const MOVE_STOMP            = 23;
const MOVE_DOUBLE_KICK      = 24;
const MOVE_MEGA_KICK        = 25;
const MOVE_JUMP_KICK        = 26;
const MOVE_ROLLING_KICK     = 27;
const MOVE_SAND_ATTACK      = 28;
const MOVE_HEADBUTT         = 29;
const MOVE_HORN_ATTACK      = 30;
const MOVE_FURY_ATTACK      = 31;
const MOVE_HORN_DRILL       = 32;
const MOVE_TACKLE           = 33;
const MOVE_BODY_SLAM        = 34;
const MOVE_WRAP             = 35;
const MOVE_TAKE_DOWN        = 36;
const MOVE_THRASH           = 37;
const MOVE_DOUBLE_EDGE      = 38;
const MOVE_TAIL_WHIP        = 39;
const MOVE_POISON_STING     = 40;
const MOVE_TWINEEDLE        = 41;
const MOVE_PIN_MISSILE      = 42;
const MOVE_LEER             = 43;
const MOVE_BITE             = 44;
const MOVE_GROWL            = 45;
const MOVE_ROAR             = 46;
const MOVE_SING             = 47;
const MOVE_SUPERSONIC       = 48;
const MOVE_SONIC_BOOM       = 49;
const MOVE_DISABLE          = 50;
const MOVE_ACID             = 51;
const MOVE_EMBER            = 52;
const MOVE_FLAMETHROWER     = 53;
const MOVE_MIST             = 54;
const MOVE_WATER_GUN        = 55;
const MOVE_HYDRO_PUMP       = 56;
const MOVE_SURF             = 57;
const MOVE_ICE_BEAM         = 58;
const MOVE_BLIZZARD         = 59;
const MOVE_PSYBEAM          = 60;
const MOVE_BUBBLE_BEAM      = 61;
const MOVE_AURORA_BEAM      = 62;
const MOVE_HYPER_BEAM       = 63;
const MOVE_PECK             = 64;
const MOVE_DRILL_PECK       = 65;
const MOVE_SUBMISSION       = 66;
const MOVE_LOW_KICK         = 67;
const MOVE_COUNTER          = 68;
const MOVE_SEISMIC_TOSS     = 69;
const MOVE_STRENGTH         = 70;
const MOVE_ABSORB           = 71;
const MOVE_MEGA_DRAIN       = 72;
const MOVE_LEECH_SEED       = 73;
const MOVE_GROWTH           = 74;
const MOVE_RAZOR_LEAF       = 75;
const MOVE_SOLAR_BEAM       = 76;
const MOVE_POISON_POWDER    = 77;
const MOVE_STUN_SPORE       = 78;
const MOVE_SLEEP_POWDER     = 79;
const MOVE_PETAL_DANCE      = 80;
const MOVE_STRING_SHOT      = 81;
const MOVE_DRAGON_RAGE      = 82;
const MOVE_FIRE_SPIN        = 83;
const MOVE_THUNDER_SHOCK    = 84;
const MOVE_THUNDERBOLT      = 85;
const MOVE_THUNDER_WAVE     = 86;
const MOVE_THUNDER          = 87;
const MOVE_ROCK_THROW       = 88;
const MOVE_EARTHQUAKE       = 89;
const MOVE_FISSURE          = 90;
const MOVE_DIG              = 91;
const MOVE_TOXIC            = 92;
const MOVE_CONFUSION        = 93;
const MOVE_PSYCHIC          = 94;
const MOVE_HYPNOSIS         = 95;
const MOVE_MEDITATE         = 96;
const MOVE_AGILITY          = 97;
const MOVE_QUICK_ATTACK     = 98;
const MOVE_RAGE             = 99;
const MOVE_TELEPORT         = 100;
const MOVE_NIGHT_SHADE      = 101;
const MOVE_MIMIC            = 102;
const MOVE_SCREECH          = 103;
const MOVE_DOUBLE_TEAM      = 104;
const MOVE_RECOVER          = 105;
const MOVE_HARDEN           = 106;
const MOVE_MINIMIZE         = 107;
const MOVE_SMOKESCREEN      = 108;
const MOVE_CONFUSE_RAY      = 109;
const MOVE_WITHDRAW         = 110;
const MOVE_DEFENSE_CURL     = 111;
const MOVE_BARRIER          = 112;
const MOVE_LIGHT_SCREEN     = 113;
const MOVE_HAZE             = 114;
const MOVE_REFLECT          = 115;
const MOVE_FOCUS_ENERGY     = 116;
const MOVE_BIDE             = 117;
const MOVE_METRONOME        = 118;
const MOVE_MIRROR_MOVE      = 119;
const MOVE_SELF_DESTRUCT    = 120;
const MOVE_EGG_BOMB         = 121;
const MOVE_LICK             = 122;
const MOVE_SMOG             = 123;
const MOVE_SLUDGE           = 124;
const MOVE_BONE_CLUB        = 125;
const MOVE_FIRE_BLAST       = 126;
const MOVE_WATERFALL        = 127;
const MOVE_CLAMP            = 128;
const MOVE_SWIFT            = 129;
const MOVE_SKULL_BASH       = 130;
const MOVE_SPIKE_CANNON     = 131;
const MOVE_CONSTRICT        = 132;
const MOVE_AMNESIA          = 133;
const MOVE_KINESIS          = 134;
const MOVE_SOFT_BOILED      = 135;
const MOVE_HI_JUMP_KICK     = 136;
const MOVE_GLARE            = 137;
const MOVE_DREAM_EATER      = 138;
const MOVE_POISON_GAS       = 139;
const MOVE_BARRAGE          = 140;
const MOVE_LEECH_LIFE       = 141;
const MOVE_LOVELY_KISS      = 142;
const MOVE_SKY_ATTACK       = 143;
const MOVE_TRANSFORM        = 144;
const MOVE_BUBBLE           = 145;
const MOVE_DIZZY_PUNCH      = 146;
const MOVE_SPORE            = 147;
const MOVE_FLASH            = 148;
const MOVE_PSYWAVE          = 149;
const MOVE_SPLASH           = 150;
const MOVE_ACID_ARMOR       = 151;
const MOVE_CRABHAMMER       = 152;
const MOVE_EXPLOSION        = 153;
const MOVE_FURY_SWIPES      = 154;
const MOVE_BONEMERANG       = 155;
const MOVE_REST             = 156;
const MOVE_ROCK_SLIDE       = 157;
const MOVE_HYPER_FANG       = 158;
const MOVE_SHARPEN          = 159;
const MOVE_CONVERSION       = 160;
const MOVE_TRI_ATTACK       = 161;
const MOVE_SUPER_FANG       = 162;
const MOVE_SLASH            = 163;
const MOVE_SUBSTITUTE       = 164;
const MOVE_STRUGGLE         = 165;
const MOVE_SKETCH           = 166;
const MOVE_TRIPLE_KICK      = 167;
const MOVE_THIEF            = 168;
const MOVE_SPIDER_WEB       = 169;
const MOVE_MIND_READER      = 170;
const MOVE_NIGHTMARE        = 171;
const MOVE_FLAME_WHEEL      = 172;
const MOVE_SNORE            = 173;
const MOVE_CURSE            = 174;
const MOVE_FLAIL            = 175;
const MOVE_CONVERSION_2     = 176;
const MOVE_AEROBLAST        = 177;
const MOVE_COTTON_SPORE     = 178;
const MOVE_REVERSAL         = 179;
const MOVE_SPITE            = 180;
const MOVE_POWDER_SNOW      = 181;
const MOVE_PROTECT          = 182;
const MOVE_MACH_PUNCH       = 183;
const MOVE_SCARY_FACE       = 184;
const MOVE_FAINT_ATTACK     = 185;
const MOVE_SWEET_KISS       = 186;
const MOVE_BELLY_DRUM       = 187;
const MOVE_SLUDGE_BOMB      = 188;
const MOVE_MUD_SLAP         = 189;
const MOVE_OCTAZOOKA        = 190;
const MOVE_SPIKES           = 191;
const MOVE_ZAP_CANNON       = 192;
const MOVE_FORESIGHT        = 193;
const MOVE_DESTINY_BOND     = 194;
const MOVE_PERISH_SONG      = 195;
const MOVE_ICY_WIND         = 196;
const MOVE_DETECT           = 197;
const MOVE_BONE_RUSH        = 198;
const MOVE_LOCK_ON          = 199;
const MOVE_OUTRAGE          = 200;
const MOVE_SANDSTORM        = 201;
const MOVE_GIGA_DRAIN       = 202;
const MOVE_ENDURE           = 203;
const MOVE_CHARM            = 204;
const MOVE_ROLLOUT          = 205;
const MOVE_FALSE_SWIPE      = 206;
const MOVE_SWAGGER          = 207;
const MOVE_MILK_DRINK       = 208;
const MOVE_SPARK            = 209;
const MOVE_FURY_CUTTER      = 210;
const MOVE_STEEL_WING       = 211;
const MOVE_MEAN_LOOK        = 212;
const MOVE_ATTRACT          = 213;
const MOVE_SLEEP_TALK       = 214;
const MOVE_HEAL_BELL        = 215;
const MOVE_RETURN           = 216;
const MOVE_PRESENT          = 217;
const MOVE_FRUSTRATION      = 218;
const MOVE_SAFEGUARD        = 219;
const MOVE_PAIN_SPLIT       = 220;
const MOVE_SACRED_FIRE      = 221;
const MOVE_MAGNITUDE        = 222;
const MOVE_DYNAMIC_PUNCH    = 223;
const MOVE_MEGAHORN         = 224;
const MOVE_DRAGON_BREATH    = 225;
const MOVE_BATON_PASS       = 226;
const MOVE_ENCORE           = 227;
const MOVE_PURSUIT          = 228;
const MOVE_RAPID_SPIN       = 229;
const MOVE_SWEET_SCENT      = 230;
const MOVE_IRON_TAIL        = 231;
const MOVE_METAL_CLAW       = 232;
const MOVE_VITAL_THROW      = 233;
const MOVE_MORNING_SUN      = 234;
const MOVE_SYNTHESIS        = 235;
const MOVE_MOONLIGHT        = 236;
const MOVE_HIDDEN_POWER     = 237;
const MOVE_CROSS_CHOP       = 238;
const MOVE_TWISTER          = 239;
const MOVE_RAIN_DANCE       = 240;
const MOVE_SUNNY_DAY        = 241;
const MOVE_CRUNCH           = 242;
const MOVE_MIRROR_COAT      = 243;
const MOVE_PSYCH_UP         = 244;
const MOVE_EXTREME_SPEED    = 245;
const MOVE_ANCIENT_POWER    = 246;
const MOVE_SHADOW_BALL      = 247;
const MOVE_FUTURE_SIGHT     = 248;
const MOVE_ROCK_SMASH       = 249;
const MOVE_WHIRLPOOL        = 250;
const MOVE_BEAT_UP          = 251;
const MOVE_FAKE_OUT         = 252;
const MOVE_UPROAR           = 253;
const MOVE_STOCKPILE        = 254;
const MOVE_SPIT_UP          = 255;
const MOVE_SWALLOW          = 256;
const MOVE_HEAT_WAVE        = 257;
const MOVE_HAIL             = 258;
const MOVE_TORMENT          = 259;
const MOVE_FLATTER          = 260;
const MOVE_WILL_O_WISP      = 261;
const MOVE_MEMENTO          = 262;
const MOVE_FACADE           = 263;
const MOVE_FOCUS_PUNCH      = 264;
const MOVE_SMELLING_SALT    = 265;
const MOVE_FOLLOW_ME        = 266;
const MOVE_NATURE_POWER     = 267;
const MOVE_CHARGE           = 268;
const MOVE_TAUNT            = 269;
const MOVE_HELPING_HAND     = 270;
const MOVE_TRICK            = 271;
const MOVE_ROLE_PLAY        = 272;
const MOVE_WISH             = 273;
const MOVE_ASSIST           = 274;
const MOVE_INGRAIN          = 275;
const MOVE_SUPERPOWER       = 276;
const MOVE_MAGIC_COAT       = 277;
const MOVE_RECYCLE          = 278;
const MOVE_REVENGE          = 279;
const MOVE_BRICK_BREAK      = 280;
const MOVE_YAWN             = 281;
const MOVE_KNOCK_OFF        = 282;
const MOVE_ENDEAVOR         = 283;
const MOVE_ERUPTION         = 284;
const MOVE_SKILL_SWAP       = 285;
const MOVE_IMPRISON         = 286;
const MOVE_REFRESH          = 287;
const MOVE_GRUDGE           = 288;
const MOVE_SNATCH           = 289;
const MOVE_SECRET_POWER     = 290;
const MOVE_DIVE             = 291;
const MOVE_ARM_THRUST       = 292;
const MOVE_CAMOUFLAGE       = 293;
const MOVE_TAIL_GLOW        = 294;
const MOVE_LUSTER_PURGE     = 295;
const MOVE_MIST_BALL        = 296;
const MOVE_FEATHER_DANCE    = 297;
const MOVE_TEETER_DANCE     = 298;
const MOVE_BLAZE_KICK       = 299;
const MOVE_MUD_SPORT        = 300;
const MOVE_ICE_BALL         = 301;
const MOVE_NEEDLE_ARM       = 302;
const MOVE_SLACK_OFF        = 303;
const MOVE_HYPER_VOICE      = 304;
const MOVE_POISON_FANG      = 305;
const MOVE_CRUSH_CLAW       = 306;
const MOVE_BLAST_BURN       = 307;
const MOVE_HYDRO_CANNON     = 308;
const MOVE_METEOR_MASH      = 309;
const MOVE_ASTONISH         = 310;
const MOVE_WEATHER_BALL     = 311;
const MOVE_AROMATHERAPY     = 312;
const MOVE_FAKE_TEARS       = 313;
const MOVE_AIR_CUTTER       = 314;
const MOVE_OVERHEAT         = 315;
const MOVE_ODOR_SLEUTH      = 316;
const MOVE_ROCK_TOMB        = 317;
const MOVE_SILVER_WIND      = 318;
const MOVE_METAL_SOUND      = 319;
const MOVE_GRASS_WHISTLE    = 320;
const MOVE_TICKLE           = 321;
const MOVE_COSMIC_POWER     = 322;
const MOVE_WATER_SPOUT      = 323;
const MOVE_SIGNAL_BEAM      = 324;
const MOVE_SHADOW_PUNCH     = 325;
const MOVE_EXTRASENSORY     = 326;
const MOVE_SKY_UPPERCUT     = 327;
const MOVE_SAND_TOMB        = 328;
const MOVE_SHEER_COLD       = 329;
const MOVE_MUDDY_WATER      = 330;
const MOVE_BULLET_SEED      = 331;
const MOVE_AERIAL_ACE       = 332;
const MOVE_ICICLE_SPEAR     = 333;
const MOVE_IRON_DEFENSE     = 334;
const MOVE_BLOCK            = 335;
const MOVE_HOWL             = 336;
const MOVE_DRAGON_CLAW      = 337;
const MOVE_FRENZY_PLANT     = 338;
const MOVE_BULK_UP          = 339;
const MOVE_BOUNCE           = 340;
const MOVE_MUD_SHOT         = 341;
const MOVE_POISON_TAIL      = 342;
const MOVE_COVET            = 343;
const MOVE_VOLT_TACKLE      = 344;
const MOVE_MAGICAL_LEAF     = 345;
const MOVE_WATER_SPORT      = 346;
const MOVE_CALM_MIND        = 347;
const MOVE_LEAF_BLADE       = 348;
const MOVE_DRAGON_DANCE     = 349;
const MOVE_ROCK_BLAST       = 350;
const MOVE_SHOCK_WAVE       = 351;
const MOVE_WATER_PULSE      = 352;
const MOVE_DOOM_DESIRE      = 353;
const MOVE_PSYCHO_BOOST     = 354;

var trainer1 = TrainerHelper.createDefault();

module.exports = TrainerHelper;